name: "cache nixcode"
on:
  push:
    branches: [master]
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dcarbone/install-jq-action@v3
    - uses: cachix/cachix-action@v14
      with:
        name: nixcode
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixcode-cpp
    - run: nix build .#nixcode-jvm
    - run: nix build .#nixcode-nix
    - run: nix build .#nixcode-python
    - run: nix build .#nixcode-rust
    - run: nix build .#nixcode-web