name: "Cachix"
on:
  push:
    branches: [master]
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dcarbone/install-jq-action@v3
    - uses: cachix/cachix-action@v14
      with:
        name: nixcode
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixcode-cpp --json | jq -r '.[].outputs | to_entries[].value'
    - run: nix build .#nixcode-jvm --json | jq -r '.[].outputs | to_entries[].value'
    - run: nix build .#nixcode-nix --json | jq -r '.[].outputs | to_entries[].value'
    - run: nix build .#nixcode-python --json | jq -r '.[].outputs | to_entries[].value'
    - run: nix build .#nixcode-rust --json | jq -r '.[].outputs | to_entries[].value'
    - run: nix build .#nixcode-web --json | jq -r '.[].outputs | to_entries[].value'
    - run: nix-shell --run "echo OK"